/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

! function (B, A) {
    "function" == typeof define && define.amd ? define(["exports", "echarts"], A) : "object" == typeof exports && "string" != typeof exports.nodeName ? A(exports, require("echarts")) : A({}, B.echarts)
}(this, function (B, A) {
    var D = function (B) {
        "undefined" != typeof console && console && console.error && console.error(B)
    };
    A ? A.registerMap ? A.registerMap("主城外圈", {
        type: "FeatureCollection",
        features: [{
            id: "500102",
            type: "Feature",
            geometry: {
                type: "Polygon",
                coordinates: ["@@DEJGNQFC@C@CB@NHBBDAFE@CAAAGBCHGB@VHBTJNDDFCBELKBBDBDEH@JCBECELGAEBABAFABCF@DCJDJFJ@FMAG@AGAACAENQNGFADEBBF@DCBEFGAKFKGQNIJKbEUQEKBCAAQGCSKEEEDCNADC@]AE@ABKLGJCJ@HDRPJDBE@]AEAGBaFOFAEAEDEKEAEGGABCHAFKJEBEAUCIGGBKEW@EFELEFI\\ATQFADC@OFGXFHAPIfGF@BAEKEOYiCC@ADABCECDCAGEEGCEEG@AIGCACEGEIIGEI[YCQSMWK[GEBGCAGAIDMCGHCHADEBC@MBCBCACDU@CSEOBGBE@EAY_ECCG@EAE[@MGECCKEG@IIEKIEACJOXI\\GNQPOTa^EJCRG@ICGAACBEOGIIGBCFCACABISECBBFITBTCBEAE@@DBDCFODCHIHOF@FIBGEGCEEKCC@IDUOS@SEG@EACC@GEIYYAOKO@GAEIIc]OKMEE@EAEE@CDA@AMEQCEFGAAAAEQGACFC@CEG@CFCNQH_BAACDSEEM@QFaACBBBJJEDADANBDLTBFABK@GEE@ABDRFBBBCFE@EDIEMDA@CAFCAAC@ADCBEAECA@CBCBEVKFAA@EGEC@KDCECCQE@AFCJABABCAI@AF@@ACEGCKDEAKGAEA@ODC@CCCDDDCBMI@AFIDFFQDKBC@CECWCO@OCSDCBELM@EHI@KFIDABDDADBBBDF@@DFD@BBDCDC@ICE@CD@FABCC@GCAKJEJ@DJBHH@BEAABCJ@HE@@DFDEHC^BDPNDFCX@DDDEFGBMAECABAH@LBHFH@BCBMCCEBIGMCAI@ABDHILUHIFG@OBIAABAFIBEDOBD^FNF^@pDVFT@LPbF^DFH\\@HDJLVBBF@BBELFHBPJTBNJ`FZLCXJN@RPBJHDBFVFJNHBLJHBADBLP@NFdORRD@^RPHPJRHFAH@NJHBFD\\FBD@DLHBFFJ^L@DGDCF@DFJCHBDBBDHL@JFN@HADAL@DDDDJA@BADDBD@BEJ@FBGLDBLKHBBFB@DEBKECAAFCZDHCHADBFD@HDJHBJEH@VNHHFRDBBBADEB@DPBBB@FADCD@D@BHFBJDBFCB@FFTDPRFDLIDID@@DCZPPDFADED@DTVVbX^FDBCBEBBPPDJRPPVFBFBBCFALBHABGHCAE"],
                encodeOffsets: [[110051, 30710]]
            },
            properties: {
                cp: [107.294905, 29.653652],
                name: "涪陵分行",
                childNum: 1
            }
        }, {
            id: "500110",
            type: "Feature",
            geometry: {
                type: "Polygon",
                coordinates: ["@@GDAFSBAFJLBXCFMJC@KEI@OHCDCLC@CCAKGGKCC@KJM@GHANBDHF@@CBADIEGDE@UIINKFEFE@KCEA@CBCLGBOCEA@O@OGKAEBAD@HBHCHBHFDBDABKDAFBFJJ@BFFRBNCDBDD@JBBRHDBBF@DDDVJDBB\\CLCVKX@FJ\\FDDANGHAHDDDFH@BALDLCFAFKA@JSFCHBFFDF@XCPBNDDFABGTIHC@IKGAIDMJCF@JGJ@FJLBB@DCDE@QKGDCFCDCBE@MIBHITKBGD@BBF@BG@SXAVJ^ANCJYXC@KAMDAFDDAFEBK@CB@JCB@FDBABAB@DC@CAGDI@ONEBEDGBAFGLQTERKBGCECEHABCBCFCN@LCFGDBNUNOBEDMACBAF@L@FGLBRCTAPBJObL`ADIHEFHRDP@FENIHCD@NALIJFH@HABIFEF@BHBNAJCNLEFFFVPJDLALEHABEHACR@DD@JCFAFEVC@AECYAI@AAHI@IHGHKJCVALEDFBHDDEHDDDJNLBF@JEPEVJTCH@DBFDBXMAAEA@CJIDIHCLAHGDMJIBCAGBCf@BCBALO@AIIBEHEGEAA@CD@@ED@HBBA@@DJBBDBDHDANNHABDDALQBIDCJ@VHFFFDA@CBK@IDKXGpHHCFGVCD@FFH@DMXBHFZADIDADDRCHPHFABGDARFD@FCFANH@N@BLHEHNNDNHHPLFAH@DDCFBBN@F@BDDAE]B@JBF@HED@DFANBBDAFLDFFA@EB@FHDTBBJCHELMD@@DVBHEBEXUJFDDBFRHFFPEACDCLADBB@AKDED@PFPTFFF@DMBAFDALBDFBJAHADA@IBKJKDQDCHAH@JHRDHDFBFAHEFKF@DFFBbQDADKJIJOROLAHEFGFO@CAEACGAHGGI@GEC@CGCDICEEA@ADCCK@IDAB@@JDBFAFCBCDIJADDD@JIBFFBFCCA@AD@JFGH@BD@B@@JFP@FBFFFDID@BACCBGBCFADDF@BEHCCE@AD@FFHEDDCFBBPEBACALOMEAA@KACJE@EJIDADBFATKNODIDEPEJQ@IGACKCAI@EGBICE@EFOH@FKFCFEL@FBFFDBLCNIDK@GCEAIACE@KFAABEFCFI@GDC@EFEFIMICGAKEIFCVIO@YIABAFDVCFUDSAAIDGDQ@IECUBAECCIAOBMEFSAEFGBICGCA@EAC@EEG@C@CBCAEDEBACCFA@CDA@CDCBG@GCC@KGCMAABOBGGEAMCE@ABAFBNCBIDEFADCNADGJCHA@GLEBECGGIEGGCAOJC@ECUQOUIGIAC@@JCBOAOBIGAQACIFAAQW@CHSBMDGDAJDBABENCJET[DIOACC@EDIJILCLHN@JALF@GCEAAGBACAE@GGMAIGSIK@EFAAWCMBEAEICK@c@GBIAAG@CBAHEAEIM@GAAOAIMAAI@ENILKFEPBHMTGAGGAC@ICEQDIACCCC@CBMBC@GAG@CROHEJ@JEDG@EEGUCCACECAGBI@QIMBUWAKEMBMBGHMHQBANIBCDKBOAODI@E[ECCAEEGC@QDGCGGA@"],
                encodeOffsets: [[109269, 29134]]
            },
            properties: {
                cp: [106.701417, 28.900091],
                name: "綦江支行",
                childNum: 1
            }
        }, {
            id: "500111",
            type: "Feature",
            geometry: {
                type: "Polygon",
                coordinates: ["@@DBHNLJABCBIIE@G@EF@DFDFFBD@HFDBD@FAFABACC@AFBDDNNL@DELCDG@IF@DD@@BADSTCA@CIAMKOCAE@ECCGBBFABK@WLE@@DJDCBAJA@C@CCBGCBABEFAH@BBD@BCDDJ@DKHDHFLB@FEDBBDADBDABECSCECCFAJCFCDACACDGE@@CDCAKDCJABGCAIDA@DIECAEEJI@BJBFABEDE@EFADBN@DCDIFMBMEKAABDHDFADEFCBEAACI@BPBBHABBJ^@BGLADDFDBNF@DEF@DBHJ@@BEDBD@BGHGBDFAFABEBAFFD@DC@MCEFGBEAM@GAEAEKIG@CBAACECEAE@CDCLBDBJADEDEBAEI@BFABGEA@@BC@@EGAA@AFEHGTINBdHTCDKDDJQF@HGLEDAFDJDF@DCDMHENBJ@FABC@EBENBJHLFFJFNBDCFKFE\\GNCBCDGJIHBNB@FKHELNJF@DJRJ@BCBKDBNLJJMHGPEBBBHADADCF@DDDCBFDRDANDLIHAF@DDH^^AFE@EFF\\BH@JBDCHBBFBBDBBBCNENCJHBDADEFDDDADBCH@FFBBFFFDFFA@A@CHCJAVEFHPBHFFABCDAHHH@BFADBBPHHADAL@DKHEFAFDD@BCHCFB@DDBFFHD@BAF@HHDF@JDD@BCHC@WAEC@ABIEGOBAD@JIBIDA@CACE@GGIEEKKOCIDCD@JC@DJ@BDTJJBHHDCD@BB\\MD@PRDABB@FDH@FFEBEAEDCB@BCHA@GF@NG@EDCDB@DJC@ECMBKDAF@RHBABEDCCIBCNEjAPBTAHFDHHJCDBFVBBBBHHLKJJJ@HADDDFAFBFIHEIIDIRBFDFAHBHCBEJBHGHCBAFCFHJALFRCF@HFFDF@FAF@DEFBBA@AFAACD@DC@IFCCWFABACG@ALCL@DBBHFEFBDDLCBAEGDCBEEKVOKKKOKWOSKSAGKYAAC@OLGDA@EOSeecC@C@CAKQCKBAEAW]AAEACGGCIIG@GICAEASSGOKEGGAE@CHIACECGAI@KFE@GEECOEKIQ[AIGQ@GEKCUCI@CIGBKCG@GCGCSECBA@CCICCG@IKGAGKC@EMKC@MFKK_ECC@CEIAAECDEEABCBBBE@@FEABFE@BBIFCDKB"],
                encodeOffsets: [[108267, 30091]]
            },
            properties: {
                cp: [105.755319, 29.640498],
                name: "大足支行",
                childNum: 1
            }
        }, {
            id: "500115",
            type: "Feature",
            geometry: {
                type: "MultiPolygon",
                coordinates: [["@@LDFARYJYFGHERADEHSBCFAPCVBBFGJCJJPD@D@HCDODC@GHH\\JHF@HRR@DQNAB@DDBBDGD@DNXFBX@DABGDAFBAHBDPP@HEBAJBFFBD@JC\\LDDBFDPNJPR`VNLNPJNTRFHPLRTLJPXFGNCNITKJKBE@CA@DCF@HIBCPMJEJADC@GEIKMGKMO@CBIDED@\\DD@FIDEBOEMIGAGHSIMC@UFC@CI@CBEAEMACC@CAAKBKADGHEVKBA@I@C\\MBAEGLAFDN@ZKFEH]ICECNO@CACQ@GAEE@G\\KBCDIFAXUHALDPHJFL@RANEJGFDjnZXPLLRF@HFFND@VKHIFCNKQM@CDIKCOUQOCIMOCAAFADMKOUOYY]@CFCBCCEOODY@CC@CJKJECOQSCEEA@EDCAAIGE@A@CDCBC@EAAOA@CFABCAACAEQGGUMG@IFGACI@GECCAGBGDYCEDBBFDALCFA@AEGAKLCAHKEAI@AFC@CABC@AIBCCCCK@CBGBM@IEK@CGAAACDGEI@CDEHC@C]KEIAEKG@CAC[EECGAMIG@EBQGOIOG]QC@QQcPMEO@AKBCGAKIGAIMUEAEGCAIOMAAM@QGGAIDEFCRBLADKFCBDHAFCHBHFFBFAFEF@DAFEBGAICIEEH@FEB@DCBCGGCAPABEDAJC@KADLH@DDABGDBFQNJR@DCB@BBNBDCLABBDBHCDIDAF@JDFPHDTCPBHLFTlFDRXP\\FHMJKAC@E\\WFA@AEKBABEN@HA@E@I@CB@DBLEDIACBABA@A@CCGAA@@CKBGHG@EBCDBHADKFEA@KAAA@CBBFABKBCCBGMCINBPAH@HDXEBK@CBAD@FBDJFDDCDJBJDPBLFD@BABCBAJBNAD@HGDCF@DBBPDBTD^LD@BIB@DBDFBJFJDBDD@NKDABLFVZDDPD"], ["@@A@A@D@"], ["@@ABBA"], ["@@A@@@B@"], ["@@EEA@@FB@F@"]],
                encodeOffsets: [[[109544, 30806]], [[109545, 30811]], [[109549, 30810]], [[109546, 30810]], [[109628, 30765]]]
            },
            properties: {
                cp: [107.134854, 29.953671],
                name: "长寿支行",
                childNum: 5
            }
        }, {
            id: "500116",
            type: "Feature",
            geometry: {
                type: "Polygon",
                coordinates: ["@@BAJABCAC[OAC@ADCEGDCL@BCAEBAF@@AACEEOC@GFK@MNS@IDAFCXQFCFCFB@EHCBBBABCACB@@GFIH@BAIIFABCAAACLCLB@AECHABAECDA@CFE@CBACKFMHEBCD@FEDEDG@CG@ECCKECEASDECFMAKDC@CAGBIEICC@EBCAE@CEAGCBGCIBMHGFIJI@EFGJEVB@CGEEBA@CCBE@EAAK@GDAFCFEVELGDCAIBIFIJC@MS@EHIRODIFGBEBEZQJKBKACCAAAOHEIG@EEG@MBGFCNQFEACBABBLMFIJC@KCULEASDMJIDIAMMGADADIDABCGADGCAEAFGEEIFIIJG@CGKABC@GCADE@ADEHGJGDCBMMAAA@GLBLAJKH\\R@HK@LNBR@HAFIFBF@FADMFEFKVBT@FHH@FEDS@KFGFAHCFLTRDFFIHOHEF@JBPAJCF@LBFAFEJGF@JCFOL@FADKDEFE@CBC\\@XAHEDAJBHKJQBCTCHAREH@FDFJCHDOJAHDDLBLHDJBJDHONEL@HADOBEDIAAJSVAFBFABUDKJEPABE@CACFEBCACBCFaR@AAGGEKGM@EAEIGAI@MFOCKBMEOCM@KDKF@BDLAHA@@GC@SHEHCBOAGGAGKGG@MJCLBHDD@DABE@@BBBFBDABEB@B@BD@BCBCFEBEDDLNF@FCLEDMBICKGGBGDQVMTIFKBGDE@EAGCCEDCJ@LCBEAEIAIGCBCHCDE@KECCEOQMMMKAEGUAGGAICCMCACBELO@GCEGAGDIJKDKBCDAFDN@LEHIDIBeKGAQHGLUPIRAJFLPJdNJJBLATBhBFFJNHJBP@DBDD@LJLJJNFVHL@FF@DAPDVEDG@C@@JEDAF@H@DHFJ@@DEHBFRJPFBDAFFJDDJBDJLJFJHFBDADEB@DFBHAFBDHAHAHDTBDJDAFDJJHHFDJHDFNH@HFCHFBH@B@ZzPDLPDBAPHF@DCHFJCFDJBJAN@NHLCJBJHPPCNAJBF@NEROJK@ECGDCTMFCJJHBFAFUDCHEHDAFDFJ@JF@DJAEHBBH@DBFGDDHAJRP@NFJFhhTNNRJDJLPlRbJ\\DNBXDPNRLZDBFADAJBLCDGJC@GBCD@BHDBFEFDB@FIHDDGBOHBNBD@DCBIIECEBIBABHBBN@BA@_FA@AMEEKGACDCBCEE@CC@CDCAAIBOCAD@HCDGBE@CEAKBKAE@AKGAC@CFCBGCCUE@CAA@CCC@IEEDEFCRCBIBAJCDDDBHEAC@GCEAADKECECFSECCGLMNWFKFIHATA^JZJTRNHJDXBXFHFHJBJMb@JBHJHBTBFDD`FpVHEB@TDJDHLDBPCHFF@DABAGEHKECA[BC@KDEAMHEHUF@FAGODGFETEHGH@@EEO@CNA@GBEDAAKHADCGS@EBECEBAF@BC@ADIJ@TEBAAEDEFAJBBACYGQ@EJKLKFIBKFEF@@CGGIAECAIBGVYJCL@JMCOBEJCBCEYAGNW@CEG@EDCHUDEGGHoLWJCL@DAB@ECEEUGI@CDAJKRCBACGBMMCBCGCAAACI@@ABGAC@@FC@@DBBHFGFAFJJ@BKPABADe@ADBHADIJCNGHKBGDCJIJ@DFBBBWNCAAE@CDGISFUFO@IAEMKCICCFGCCAGCEKFUBIDGLGH@JGJBBJ@ZBFD@BUDEFEBIDC@@CDQGBAFGBKFKBICUOEEFEMKIDMBGA@AFEJEBA@GEGJIBK@MDCJGFM@ECOGQFEJGBCK_PaAIBODSAQHK@UBADANBFCPAVMAMHCDE@KDMDEDABAFG"],
                encodeOffsets: [[109017, 29523]]
            },
            properties: {
                cp: [106.253156, 29.123387],
                name: "江津分行",
                childNum: 1
            }
        }, {
            id: "500117",
            type: "Feature",
            geometry: {
                type: "MultiPolygon",
                coordinates: [["@@D@XGHAH@LFF@BEBGBKDCJABABGBGB@FDB@DAJIB@BAB@FE@AAC@AF@@DBBFADDB@BAAACCFCBCHBHRRDBC@GDG@CAEAKE@BCH@BADB@@DADBBEH@BAACC@ABAAHGBBDIFBADBBJ@CDBBF@BCHABBBABEAE@ABAF@B@CCBCJ@DDBJEDEJGDBFCFBBPADMBCECBAF@@FBBLGFFB@FCAEBADBDFFBJE@ACAA@HABCCC@ABBDDD@DCFDGQBEHFFACCDGAEA@C@@C@AL@@AEELEGEAC@CD@FDBAACBICCBAAGAAKGCA@CFCL@@OHAEML@PCLDB@BACCBC@AQUJGJBDCBKDALCHBZRF@LMFKAGC@BCKEAC@CDCN@BE@IBAHF@BCHBBHH@BGJ@DDBH@BBD@DCJ@BADA@CAC@IDAFAFB@DGFADHF@JBDBDIJEBCH@BJ@FABEB@HBHC@GAI@KJBBB@JJDHC@DFBIX@FBB\\LEJEDBDCFBBL@HCLEDGBALBJEJABDDHAH@DFBFCDBDHFFPEBBDAL@@@AFJDDDVEDDBA@CBAFABB@BEHGH@DJBFAFEFCHMFARDFNADDBX@DNCDK@CDBHADKACFEBCFLALHB@@AHBPCF@BBAHEJEFADFFFBD@LKDBBJQPJLFAP@@AJACCI@CIHCF@DHBBREJ@DDDJBBBCFEDGDCFAJFD@JE@IBCJDJAD@@D@BFDJBHACH@DJDB@BGRDFCJCBVDFNJFBFAXQFCXADCBEB@ACBCFCJAFBBADBP@@CD@AAD@@CD@@AFABEFA@QHBBABECC@CDAFDFAFSJO@CUACAAEMCAEWA@CCAACDCBBB@BCND@GBAD@BFDA@AAAFCEGD@DCDDFC@AEACEGC@CFCEAAAJMD@BFFABKEAAAAEBCD@DDNFF@FA@AOUFCRADCBIIC@E@@F@HFNFDCCKFGF@HFHABA@CIIFKCM@QAM@CD@AE@GI[IMMQEAU@[KIGEGIEoeCEBGLGBA@IEE[QQMCE@QEK@MOaGYUsAASPOHQiC@MFGDCIEGEAGGCKACEAM@EAACCAFCAICCE@BAF@ACBACIIAEEAEDGAECEWIAHV`IDACIMIACDDFCBCAADJJBDC@E@ABFDFBBBJV@BC@@BDFDABDHX@BKBK@AAFC@AOaIECAIBAHABE@ECAA@CBAH@@KDEIKBCA@EAQFIDEHSLEFCJALDFALGJGDOGQKOGEEEC[O_UQGACAEIEc[mkIPHVDDD@BDADCDCBADDDHDJIBBDJALFTADC@AAOOC@CBADDJCFC@I@ADE@EDAB@BCBGFBBA@CBADGBHH@DIBMCCBBFABE@ACE@CD@NGFC@@EEBCAAFCDB@ABIDCC@GK@EEKCGFC@CKMAE@IEA@ONG@CDIJIDA@@CHCBA@EGGEAI@@BBDCFLNBFADC@EGI@GFAJIHC@EAEBLHBHAJFFHFAL@DDHFDKN@JDDHD@FYFQBiCKBuIIBGBC@CAGIEAC@CJBJHD`HFD@BCFeRSNI@WEGBONKXENAJ@JJP@DIN@JFJLJADGJ@DNFFFDFDBBDILADDFFLCFMB@DSLEHAH@FHHNBBF@FGFCFOLCHCF@DBDFDB@BABEJEJEHAD@JFFHLHNPDDHBBB@DKNKFGH@TIAGJAF[DFH@NDHTRVFJFDJ@HGHOFCDOEUDAFHLABO@CBGTCPBBFCHADJVRMJAFBDFLABCBAD@FBBNHBLCLOVAHLDBADAHGFAHBDDBJ"], ["@@EFDFDEAE"], ["@@@A@B"], ["@@AABB"], ["@@@A@B"]],
                encodeOffsets: [[[108545, 31106]], [[108811, 30929]], [[108715, 30640]], [[108790, 30630]], [[108795, 30627]]]
            },
            properties: {
                cp: [106.355554, 30.10003],
                name: "合川分行",
                childNum: 5
            }
        }, {
            id: "500118",
            type: "Feature",
            geometry: {
                type: "Polygon",
                coordinates: ["@@AICUEEAMEICKAIDWEgBGACGO@GDA@G@EEGBKIQ@GACCI@E@IDCCEKACCDCFBBA@IBAHCBA@CCC@E@QKUW]BE@QEOCC@EISAIDIGK@MBMAICIDEEIDGAEECDOEAKOOCYyA@G@EADGGEG@EMGCCIGEIGCIBEICACCSBG@KEEIBGCJGACGEEIKICIIACCEIBEACWIIGACFG@CG@EACC@IBGFCBIJ@FCCUBOAGEAI@UGMEIIIK@KCCCAO@IAMGEIAEAgBSAKIIcMOIEKBILSMEQBGAOIEAEBCFEJBHFDLCD@JRKBCBGNGHIRSDEHIBILGB@BFPCFFF@NEHC@BDOJ@DCD@DE@BD@DG@ABDBABBDE@ABC@DHF@CFHDBDFDCDHP@BBBBDB@@FCFIBKFCLAHAFUVAF@HFXFJdN@HCFEBEBCAKKG@CBCD@LDLABCBBJADBBGLITEDK@E@EBCF@FFH@ZCLFJJXCBC@EFF^KVQhCVBJDHJBbDBDCFUHGAICKIGEGK@OSAEBGBSRUD@FORENGDDBFFGBAD@D@BF@BFBBLCH@FTFDFF@DGJ@DFH@FDBD@JEBAJDPPVDFAFBDDDJJFHBH@B@@FAB@FFAFBHEHF@BFDBFCDFDPADCJEAAF@AEFB@EF@AADABAFFDCBFLBBFD@FBDHHZEL@NLDFND@HLHBJLH@DDDJ@DABFDDTDH@HDHALJH@DDJDVFL@HHRBJLRFJLJPFFDHFF@PEL@DDFFGJBHHJLFDJJNBAL@BACCBAJAJCAC@AB@BCGK@GDEFCFIVA\\JDDAD@DABBBPCBGBABBFHB@FEDIACCBAADEDABBABDBHAL@PLB@BGL@@AGADELL@FPABCEIFGAC@EBAH@DCPEHBFLDB\\DP@`HNAH@HFRTTB"],
                encodeOffsets: [[108636, 30256]]
            },
            properties: {
                cp: [105.894714, 29.308748],
                name: "永川支行",
                childNum: 1
            }
        }, {
            id: "500119",
            type: "Feature",
            geometry: {
                type: "Polygon",
                coordinates: ["@@PBNHNADAFOBAF@BABICKBGFCDBDALGHCH@FDD@FCLCBAACD@VFBMHEJ@PDN@FD@HDBPGVCDE`KNI@AMUGQEEGEAA@CDAFDF@FEJIFEGG@GPAPFHAFAFEJ@HEGICKGEACMOE@AE@QCGDMACDQCIIMFI@WFAB]LMDAFICEBCGK@OBIFADCJBF@FIDABEGMAKEEAICC@CIQABE@ICOCEBEFIDQBEAEG@CNa@YBGFATFHQBSAICCUIECACBE@CG@CAOSAAHMBMDCFAdDJADCJKDGBSR[NGF@^BDGBKACMSMCECEEEQEECGBE@GDCCIFGCGI@EDCAUeEG@CDCBGKGEMECEBMAKEE@CHEBYKC@KDICEEBGFCRGBC@GCAMEGKMKQE]AUI]COGOEGGIODMAKAEGEG@]NUHENFNELEFET@TDJFJBHPB@JFBABE@MAOF[@DRTjEHSJBBHBIVEAECIMADDJABIGOEG@QFEACIKACDAF@JABDWBCAAAGYCCGCOAIGIAKDADFPFBNBHNG@KRECEDG@BBGLCB@FCD@HEJCBCDBFLEDABBDF@HDJCLGJOHC@GGEAK@EFEDELG@EP@FDFCHBDFFNBBBBJHB@JIROFCFCJSTQJEACBIJ@FIFBD@LBBNFKPDBABOFAADECCGFEEC@@BDFGDAFE@CCEBADAHDDABC@CJEEAE@EEO@IA@C@@AHGIEC@@BDBEDEAAEIJC@CCIBCJADABEDGA@ICBAD@FDLCD@BHFALHD@DFD@HHJGHHBBDBF@DEPEHGFKBGFIJIPDJCLFHHRNFHFEL@FJDGLBDA@GAGBGBAFBP@BDBFCD@JFAFJBBAAE@EFADOHCFHLCVBDAFBBFLBBFH@@CB@BDP@BBABEAE@ABAHCCABED@BDFNDNZDC@GBA@PLFEBIEC@UZ@HBHAD@JAHAJGDEAE@AJABC@GGA@@XCVEBOBADATFFGNDXCJ@FDJADABBPAHD¸@HB@JGFABBAJFF@^DR@TEPBJ@NBJHH@NHTDRBDPAFCJABEBAJBPAH@JEVGJKCGBAJ@DBHNAJDFNDDA@AEGAG@KBGBAFDNBHAFECC@CDWCEOMACD]FGEC@CF@@GDIBAFB@AGGIA@C@CFELIDB@HDDBA@EDCTDDCAC@AEC@CE@CEBECABAJCHCNAFGN@FKDATCPDP@\\HBDEPERCEEJ@BNJDACCDCDDD@PCB@BFLHFBLCHDDF@BE@@BBJADABIBEFBBPDDDDFLCD@HF@F@BD@JEFUDADAB@FDFBDABCD@BBEDDBB@NCJFFCF@DEAAEACQBAF@HFL@BAAEKSACBMBCFCIIAADAbBREN@FFCTBD"],
                encodeOffsets: [[109816, 30085]]
            },
            properties: {
                cp: [107.178153, 29.156646],
                name: "南川支行",
                childNum: 1
            }
        }, {
            id: "500120",
            type: "Feature",
            geometry: {
                type: "Polygon",
                coordinates: ["@@ACBC@SREDDBFFAIWE_BCDADJD@@CEODCLBDEACCAKDAACCAGDIEC@CHUACCAKYMQCOAWGUWuMeIOKEMQSMggIEMEO@IQGBCCEHCAG@AAFGIB@CIEI@CEBEGCGFCDEVEBGAIIEDSNCDDH@FILQPMFE@IAMBODBD@FDDHTCVX\\LV@R@FDD@DABGDAB@JABEACDDDLBDFCD@J@FDJBD@HJRALFH@F@HCB@HHPBDAHFhC\\FRFJBNFFDVBJBBCDAHHJF@DDR`HbFHBJJRAHEFJVHVHDHRLJNPNHLBJPH@BB@FEDLPBDADIP@DM@ABBNDFDLFFBLAHFNBPDL@BGDIJ@DLDDDJHLBNTRLbLhZxxDHPR\\ZvnJFBFHGBENKBCBEAEFIJBDA@CACIMBAF@DEHBFA@AKUFALHBCECAGAKBGACHGFAD@FFF@LCTBoyIE@EKMICEDCDEBCCEGGEAC@KGMBCIMCECSOsCCE@ADCAAEBECAEBCHAB@QECBC@K@QBAHBBOFGEOGAAC@ODENCDEECKBG@IKDCHCFABAIIGSCAC@ECM_AMESHICAGBCQAmDM"],
                encodeOffsets: [[108804, 30242]]
            },
            properties: {
                cp: [106.161126, 29.523581],
                name: "璧山支行",
                childNum: 1
            }
        }, {
            id: "500151",
            type: "Feature",
            geometry: {
                type: "MultiPolygon",
                coordinates: [["@@@MHQJSPQJAXFJ@TM`MHEBC@AEC_GGCAIDID@FBHJDBD@HAJAvJLAjDRAZE@EGCCC@ILMECCG@CBKGEEEBIAGKGFAFBD@JGBIHEJ@FHD@BCAEKMDEAC@AJ@FBHH@FABGD@DB@JCJIDCH@PMB@FDDAADB@F@NBDLD@HELDFFL@BJBBD@HEA@DCBEDBFA@FD@HE@MDCF@BDF@BAAEDANDJA@CGEBAAADA@AFBLKDA@AFEH@BCJ@D@DECIBCDAD@RRD@BAEUBKCIAAIJGCCCBCDADCBCACC@CCGUJOOQCGssKKeU[GQKMSKAIGCCKC@CJIHC@ACKAOEMBGAKEECKCEAMBAN@@CJOBCACKOFC@EAAG@IOKAMGMOKIGQGCGUIUFEBGIQAIEGE[KWIQG@GIBGDC@@EAOAQSGEG@MB_GO@[CCCCGGCQFCDC@E@@DBHEHFJADOB@EKKCFHB@BK@AHA@OKK@GBCABAAACBCFBBDABDCJEFA@EGAAABAHODAABA@CBCCC[IUBEJEDCF@HHLADA@@BBDIDIBABDDABK@ABNLFBDBHJH@JJHDDHFBBBX^FBABDLLRDBD@D@fdTfFPB@HCPKD@BBLZBHLTPTLXLPLLUPFLAFCDFHABKDCCEAEFAGCAK@KD@BDHABEBBH@JBDADCB@JCDC@BDEB@BABEAEFC@GBE@CCEEA@WDKEIBEGEDABGDGHIAAFGDGAEBECQACJJJGFEJEAEBCCBC@GIILIGKAGAAUAAEDCGICGEEUBOAiBMFABDLGJQEE@CBALDN@FID@CCACD@FMHE@@HGBADA@CDBFAFCDEBDDLH@DDFHJHBJFJADBBD@JBHV\\@FJ^BRH@NGF@DDALPTF@DANDB@DCFGL@JNBADACMBCF@DHHAXKH@BACA@AB@F@HADCAC@OFCFAP@JFFHABAFEBHJBFJJDBH@HDBNHPCFIFMXIDCF@BJADDHHBDIREACDFNEDM@@BBFCFGBKEC@CB@FBFADGB@LBFLRFFADI@MDEHSHGFOBQCC@ABAHBBHTHJ@BIHABFRAHBBDBHABDDADF@@F@BCD@DEDBBDFCF@@JFH@DMJAD@DPDDNABGB@BCDFFDHFBADDFDBBADDLBBCFCB@@BBBHALEBOHEHCDEACKEDIVCF@BB@LLHAJJBHAJEBA@IFE@EJA"], ["@@@CABBB"], ["@@FABAEABBCB@B"]],
                encodeOffsets: [[[108525, 30783]], [[108714, 30641]], [[108789, 30631]]]
            },
            properties: {
                cp: [106.094948, 29.839944],
                name: "铜梁支行",
                childNum: 3
            }
        }, {
            id: "500152",
            type: "Feature",
            geometry: {
                type: "MultiPolygon",
                coordinates: [["@@BGPUDKAKMGAA@EBCDABAEKACBENIUQCIGBGDBKBEHSDAP@BAGKBEVCPFDCPEHK@ECGIEUESQCG@MEG\\CBEHIJB@SHGLELM@CAAGACCMOKGEGIEC@GBIFIFAFABA@ECAC@CDEDGPKDEHE@EAEMAGG@EFKFGPG@CJ@DADGIOBCJKACCAEIKCEEBCHI@AKIEI@IJM@CIQIB@FEF@JABIFGBIABIKG@KAAE@UDCJLFBDCFKFCDAP@@KFGBAA@ACBED@BKACCCBEGBCEACGEEDC@AHABCCKOC@CBCNI@CEG@IE@EDACCACFC@ADE@@@CECBACEBEA@IEQBAJG@AGIIUBGBAD@RDPAHETGFGHAPC@CCCKSAOJCAG@GH@JFD@FABC@IN@FCEMDCFBFIDIIICCIB@ADEJCNWJEDEGOAMGCG@IEMUFADGGGECKAG@GDAJ@HBDCDGBG@@BDBABG@WLGBCGE@ADDNCBABIMK@EHCDA@MCCBE@OSBKCCE@MHG@AQI]@EU[AG@ICEA@IBSIEGCE@COIDECIBCACEBEGCAEGC@[NAAC@CDGGIASIACI@@CIDC@CDDJLPFLJFHHF@BD@DCBAJIJC@ABHPJFBAB@DD@ZGDADF@DDABEDADBDBDAFBJADDDGHDBD@BBDDKFGAQ@ABC@ABCFEDADBDF@DDALE@BDUVBDHFDADBFB@HDBFD@DCBBDADHHADJBHJDBCTABCLCBABBRHFBF@HF@@DAA@BBFJ@BD@BDADFDADBAAB@D@@DBDADCFJ@BB@HDDEDBDOJFFBFADIAQMG@CDAJAHGJC@MKKAA@GFAJA@GGIDGE@JGTA@EBEDBRELEBCAKGGAIFEJEBKCEBAF@TCNJJ@FGBIAGDBBEDC@ECE@IHKBCBIAG@MLINEDAHBBCDAAMB@DGDBDDBPBBBDFTFDHDPADE@EFGAEDC@EEEDI@EGEACEICAIACA@QF@BFF@FABAECACBECIDBFABDBANDFJLHPB@@CH@TJJAJEBIDAJAFBFDJLJDPIJALFHJD@H@NCF@RDDHBJAPDHDDF@NCD@BDDDCFMPA@ICKAKDMLAFGHKD@JFDCDBJCHOB@FTLBB@NBHFDH@FG\\BB@JIJ@DADEF@DBDBBCDQBCDAHBN@LDB@FBNDFCDBDAD@BADDFCACBAF@DB@CHFAFCJ@BDDD@JIDAF@@DEDCFJNBDADG@EBGCC@EDAH@BECE@ADBBDDAB@BCN@BFB@BADGBCB@BFDHAF@BJABGFCHFNHBFAFADC@CHAHHJCF@AFEHGN@FHDXDJFDJGP@JBDLFVXCHOH@DLFE@@BDDBHADDBFJL@NAFDLLHPAHCDABBDFDBBLC`RDBLCLM@CDCACBIFABCRI@AEAACEM@EFCHEH@FDAH@DVNAFBBHGPDCEECAC@@L@@AACCC@GDGDCDAFBDFHDBDCDQDBHJBDGFABD@JDBFANBBCBEB@BJDBDICIE@GCAEHKDBDFJBNJB@LIBKTENE@AECBEBAF@ZDXJDAB@AG@CPB"], ["@@HMCECBCJDH"], ["@@CCB@DBBABGEBG@GBBJNA"]],
                encodeOffsets: [[[108522, 31103]], [[108091, 30921]], [[108115, 30853]]]
            },
            properties: {
                cp: [105.801818, 30.189554],
                name: "潼南支行",
                childNum: 3
            }
        }, {
            id: "500153",
            type: "Feature",
            geometry: {
                type: "Polygon",
                coordinates: ["@@PGBGCECKBEFAHK@EBAPEEINCDCGSAcJMHSFGBEB@HB@FD@@AB@HFBAAEJ@BFFAFCBCAIACDKDCF@FBFDBDAB@DJHFLFBHBN@FBHAFENDD@@CECBEFABABECEHAHG@AACFC@AI@AG@CFE@CMECACEBCHK@AI]AAGBAAAOJ@BDFBDAFEBCCECGBALBNFNAJEDC@CAMBCFEF@FCBAAEAIJ@FIBFFDCJB@JCDBAHIBCDBLCD@DF@CHBDBDDCDEBIDEFDTDFDBAACBCACCAEFA@EKCGLG@CCIDC@AAC@ABGFEBADAAHDDD@B@BIDAIC@AFAHCPGL@BAAEHADD@FBFPDNLJB@DDBTSBC@AC@@CJEJ@BCFK@EMICMACBED@BDBABE@GAAEC@GCEIG@CFEH@F@JJDABAKIGMME@@DCAEMKGFEAEB@EBA@EA@G@GAIECICCEAEBUCOOICABIFC@CA@EEG@CHI@CEEECESG@KDAAAEE@@A@CBCHAEECAHCFMPQ@EVCTOCE@EBCLKBCAGGIQASDGDEFCFJT@FKJEBGBEEQKK[ACIA@FBNBPCBCBMAEBYIG@QJG@SHCGBAECODKAUEKIIAKFEH@HJNADGDE@cOE@UDBDCDMHOBA@BDLDFF@BCB@HAD@DDBLBBFABI@C@@DBLAFQNE@COEEIDO@QECCIIAD@TFJCNALEL@HBFfZDD@HKJAHLH@BBBDAFD@DEJBFBB@DUPERCFSJEAAGCACB@BCBC@EBMDoEBDCBB@ABHF\\J@DCJBBD@LCFBCFBDIBHDE@BDC@ADCBADDB@BA@@BAA@BAAA@E@@CA@AFA@AA@BCB@BAAGBOAEAAC@SAAGACBEJEBGAAGCCKAC@OHCFBDNFHDBF@LKPKBIFAJ@HHVEXCJU\\CBEDDFUDIfBDDABDDBCJFLBJXLLAFDALEHEJBFPJBH@HBBB@NK@EIE@CD@LBBCAEFABBAD@DLPEFABLBBLFLNLNFHABADIHCHBHDBJELAPDDPFB@JFBBCHCNGFABBDCBBDH@AHDB@BXIJHJLHFNHHAFIPIPALCNDRCJDNAFDFD"],
                encodeOffsets: [[108015, 30392]]
            },
            properties: {
                cp: [105.494061, 29.503627],
                name: "荣昌支行",
                childNum: 1
            }
        }],
        UTF8Encoding: !0
    }) : D("ECharts Map is not loaded") : D("ECharts is not Loaded")
});
